# Default values for post-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gola05/gola-ui-web
  version: "latest"
  pullPolicy: Always

imagePullSecrets:
  - name: artifactory-registry

service:
  port: 80
  targetPort: 80

resources:
  requests:
    memory: "500Mi"
    cpu: "500m"
  limits:
    memory: "500Mi"
    cpu: "500m"

pdb:
  minAvailable: 1

hpa:
  minReplicas: 1
  maxReplicas: 2
  averageValue: 4

annotations:
  linkerd: enabled
  reloader:
    enabled: true
    configmap: true
    secret: true

configMountPath: "/usr/share/nginx/html/config.js"

ingress:
    path: "/"
    appFqdns:
      - secretName: narratenet-tls
        hosts:
          - "app.narratenet.com"
          - "narratenet.com"
          - "www.narratenet.com"
