version: '3'
services:
  install-deps:
    image: node:12-alpine
    working_dir: /gola-ui-web
    volumes:
      - "../:/gola-ui-web"
    command: sh -c "yarn install --frozen-lockfile"

  build-env:
    image: node:12-alpine
    working_dir: /gola-ui-web
    volumes:
      - "../:/gola-ui-web"
    command: sh -c "yarn build"