version: '3.7'
services:

  build-env:
    image: node:10-alpine
    volumes:
      - jenkins-home:/gola
    working_dir: /gola/gola-web-ui
volumes:
  jenkins-home:
    external: true
    name: jenkins-home
