version: '3.7'
services:

  build-env:
    image: node:10-alpine
    volumes:
      - jenkins_home:/gola/gola-ui-web
    working_dir: /gola/gola-ui-web
volumes:
  jenkins_home:
    external: true
    name: jenkins_home
