apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gola-api.name" . }}-config
{{- $configFilepath:= include "gola-api.configJSpath" . }}
data:
  "config.js": |
    {{- range .Files.Lines $configFilepath }}
    {{ . }}{{ end }}
