apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gola-api.name" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: "gola-frontend/narratenet-tls"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Content-Type-Options nosniff;
      add_header "X-XSS-Protection" "1;mode=block";
spec:
  rules:
    {{- $values := .Values }}
    {{- $apiName := include "gola-api.name" . }}
    {{- range .Values.ingress.appFqdns }}
    {{- range .hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $apiName }}-svc
                port:
                  number: {{ $values.service.port }}
    {{- end }}
    {{- end }}
  tls:
    {{- range .Values.ingress.appFqdns }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
